nav:
  - Home: index.md
  - API:
    - Getting Started: API/Getting Started.md
    - Install: API/Install.md
    - Usage: API/Usage.md
    - Options: API/Options.md
theme:
  name: material
  logo: "img/logo.svg"
  favicon: "icon.png"
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate
  font:
    text: Fira Code
    code: Fira Code
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
site_name: RCSV to JSON Converter
site_author: Tiffany White
copyright: "Copyright &copy; 2022 Tiffany White"
repo_url: https://github.com/twhite96/rss-feed-creator
repo_name: twhite96/cli-converter
site_url: "https://rsscreator.tiff.run/"
dev_addr: "0.0.0.0:4000"
site_description: Docs for a feed creator CLI built with Python.
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - markdown.extensions.toc:
      anchorlink: true
      permalink: true
      permalink_title: On this page
